In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
# SE DEFINE UNA RED NEURONAL CON LAS SIGUIENTES CARACTERÍSTICAS

# 1. Una capa de entrada con dos neuronas (inputs) x1, x2
# 2. Una capa oculta con 4 neuronas h1, h2, h3 y h4
# 3. Una capa de salida con una neurona o1
class NeuralNetwork:
    def __init__(self, n_inputs, n_hidden, n_output, learning_rate=0.1):
        # Inicialización de pesos
        self.weights_input_hidden = np.array([[0.2, 0.65, 0.45, 0.12],
                                              [0.8, 0.35, 0.55, 0.15]])
        self.weights_hidden_output = np.array([[0.2],
                                               [0.35],
                                               [0.45],
                                               [0.52]])
        self.bias_hidden = np.array([0.2, 0.15, 0.45, 0.52])
        self.bias_output = 0.05
        self.learning_rate = learning_rate  # Tasa de aprendizaje
    
    # Función de activación sigmoide
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    # Derivada de la función sigmoide
    def sigmoidPrime(self, x):
        return self.sigmoid(x) * (1 - self.sigmoid(x))
    
    # Propagación hacia adelante
    def forward_prop(self, x):
        # Entrada a la capa oculta (z1)
        z1 = np.dot(x, self.weights_input_hidden) + self.bias_hidden
        print("Dimensiones de z1:", z1.shape)

        # Salida de la capa oculta
        a1 = self.sigmoid(z1)
        print("Dimensiones de a1:", a1.shape)
        
        # Entrada a la capa de salida (z2)
        z2 = np.dot(a1, self.weights_hidden_output) + self.bias_output
        print("Dimensiones de z2:", z2.shape)

        # Salida final
        output = self.sigmoid(z2)
        print("Dimensiones de output:", output.shape)

        return z1, a1, z2, output
    
    # Propagación hacia atrás
    def backward_prop(self, x, y, z1, a1, z2, output):
        # Error en la capa de salida
        error_output = output - y # Diferencia entre salida deseada y real
        print("Dimensiones de error_output:", error_output.shape)

        # Gradiente de salida
        delta_output = error_output * self.sigmoidPrime(z2) # 1x1
        print("Dimensiones de delta_output:", delta_output.shape)

        # Gradiente de la capa oculta
        error_hidden = delta_output.dot(self.weights_hidden_output.T)
        print("Dimensiones de error_hidden:", error_hidden.shape)

        delta_hidden = error_hidden * self.sigmoidPrime(z1) # 1X1 1X4 1X4
        print("Dimensiones de delta_hidden:", delta_hidden.shape)
        
        # Actualización de pesos y sesgos
        self.weights_hidden_output -= self.learning_rate * np.outer(a1, delta_output) # 4x1 1x1 = 4x1
        self.bias_output -= self.learning_rate * delta_output

        self.weights_input_hidden -= self.learning_rate * np.outer(x, delta_hidden)
        self.bias_hidden -= self.learning_rate * delta_hidden

In [40]:
# Inicialización la red neuronal
n_inputs = 2 # Número de neuronas en la capa de entrada
n_hidden = 4 # Número de neuronas en la capa oculta
n_output = 1 # Número de neuornas en la capa de salida
learning_rate = 0.1

In [41]:
nn = NeuralNetwork(n_inputs, n_hidden, n_output, learning_rate)

In [42]:
# Datos de entrenamiento
x = np.array([0.25, 0.35])
y = 4.5 # Valor de salida deseado

In [43]:
# Propagación hacia adelante
z1, a1, z2, y_hat = nn.forward_prop(x)

# Realizar la retropropagación
nn.backward_prop(x, y, z1, a1, z2, y_hat)

# Mostrar pesos y sesgos actualizados
print("Pesos de entrada a oculta después de la retropropagación:")
print(nn.weights_input_hidden)
print("Pesos de oculta a salida después de la retropropagación:")
print(nn.weights_hidden_output)
print("Sesgos de la capa oculta después de la retropropagación:")
print(nn.bias_hidden)
print("Sesgo de la capa de salida después de la retropropagación:")
print(nn.bias_output)

Dimensiones de z1: (4,)
Dimensiones de a1: (4,)
Dimensiones de z2: (1,)
Dimensiones de output: (1,)
Dimensiones de error_output: (1,)
Dimensiones de delta_output: (1,)
Dimensiones de error_hidden: (4,)
Dimensiones de delta_hidden: (4,)
Pesos de entrada a oculta después de la retropropagación:
[[0.20085055 0.6515223  0.45178466 0.12216765]
 [0.80119076 0.35213121 0.55249852 0.1530347 ]]
Pesos de oculta a salida después de la retropropagación:
[[0.24591133]
 [0.39427641]
 [0.49961526]
 [0.56713262]]
Sesgos de la capa oculta después de la retropropagación:
[0.20340218 0.15608918 0.45713863 0.52867058]
Sesgo de la capa de salida después de la retropropagación:
[0.12293496]
